In [1]:
import numpy as np

In [3]:
# Defining R matrix

R = np.matrix([[-1, -1, -1, -1,  0, -1 ],
               [-1, -1, -1,  0, -1, 100],
               [-1, -1, -1,  0, -1, -1 ],
               [-1,  0,  0, -1,  0, -1 ],
               [ 0, -1, -1,  0, -1, 100],
               [-1,  0, -1, -1,  0, 100]])

In [4]:
# Defining Q matrix
Q = np.matrix(np.zeros([6, 6]))
print(Q)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [7]:
# initialize Gamma
gamma = 0.8

# define initial state
initial_state = 1

In [14]:
# func to return all available action in a state
def available_action(state):
    current_state_row = R[state]
    available_actions = np.where(current_state_row >= 0)[1]
    return available_actions

In [18]:
available_act = available_action(initial_state)
print(available_act)

[3 5]


In [22]:
# function to choose one of the action Randomly from the list of available actions
def sample_next_action(available_actions):
    next_action = int(np.random.choice(available_actions, 1))
    return next_action

In [23]:
# sample next action to be performend
action = sample_next_action(available_act)
print(action)

5


In [24]:
# Func to update the Q matrix according to the action selected and Q learning algo
# formula for Q learning:
# Q(state, action) = R(state,action) + Gamma*max[Q(next state, all action)]
# #

def update(current_state, action, gamma):
    max_index = np.where(Q[action,] == np.max(Q[action,]))[1]  # finding the max Q val for available actions
    
    if max_index.shape[0] > 1:
        max_index = int(np.random.choice(max_index, size=1))
    else:
        max_index = int(max_index)
    max_value = Q[action, max_index]

    # Q learning formula
    Q[current_state, action] = R[current_state, action] + gamma*max_value
    

In [25]:
#update Q matrix
update(initial_state, action, gamma)

# Training started

In [27]:
#training here for 10000 times
for i in range(10000):
    current_state = np.random.randint(0, int(Q.shape[0]))
    available_act = available_action(current_state)
    action = sample_next_action(available_act)
    update(current_state, action, gamma)

In [28]:
Q

matrix([[  0.,   0.,   0.,   0., 400.,   0.],
        [  0.,   0.,   0., 320.,   0., 500.],
        [  0.,   0.,   0., 320.,   0.,   0.],
        [  0., 400., 256.,   0., 400.,   0.],
        [320.,   0.,   0., 320.,   0., 500.],
        [  0., 400.,   0.,   0., 400., 500.]])

In [29]:
# normalizing the Q matrix, as the bigger number calculation will be heavy
Q = Q / np.max(Q) * 100
print(Q)

[[  0.    0.    0.    0.   80.    0. ]
 [  0.    0.    0.   64.    0.  100. ]
 [  0.    0.    0.   64.    0.    0. ]
 [  0.   80.   51.2   0.   80.    0. ]
 [ 64.    0.    0.   64.    0.  100. ]
 [  0.   80.    0.    0.   80.  100. ]]


# Testing

In [ ]:
# goal state = 5
# Best path if we are starting from 2 is --->>> 2 -> 3 -> 1 -> 5 OR 2 -> 3 -> 4 -> 5

In [39]:
current_state = 2
steps = [current_state]

while current_state != 5:
    next_step_index = np.where(Q[current_state,] == np.max(Q[current_state,]))[1]
    
    if next_step_index.shape[0] > 1:
        next_step_index = int(np.random.choice(next_step_index, size=1))
    else:
        next_step_index = int(next_step_index)
    
    steps.append(next_step_index)
    current_state = next_step_index

In [40]:
#Print selected seq of steps
print("Selected Path : ")
print(steps)

Selected Path : 
[2, 3, 4, 5]
